DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS gyms CASCADE;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE gyms (
id SERIAL PRIMARY KEY,
name VARCHAR(225),
address VARCHAR(225),
gym_id VARCHAR,
user_id INT REFERENCES users(id)
);
